language: node_js
node_js:
    - '0.11'
    - '0.10'

after_success:
    - ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter tests | ./node_modules/coveralls/bin/coveralls.js

env:
    global:
        secure: "c7RVlvjlpDIkcOJw8Muu5H2uvgvLvZjezTjNQKxohGrKeY0JhC6fBRL10SzqCPYK9tMGzWXz6aMk0h5yqGTNMDcHtzF9Qn3wKw/p9EvEiEQZnuB+9ToELx4+EBaFJRcoZeCi2mAPU2HNOgubycsIkDMTLiDOIBcGQYZ7m0xzp7g="
